### ISSUE TITLE
 。

### ISSUE THREAD

**Issue by yu-liang-zheng** [c-rainstorm/blog#1]

**Comment by jjtxGit** [comment]
并没有 我一面的时候太紧张 导致目前还没有二面 发自网易邮箱大师 在2017年04月07日 08:37，郑裕良 写道： 你好，请问你面试阿里巴巴的职位成功了吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by c-rainstorm** [comment]
因为一面面试官评价说我技术不错，所以目前在一边准备一边等二面电话。

**Comment by yu-liang-zheng** [comment]
感觉你基础很扎实，加油。

**Comment by c-rainstorm** [comment]
嗯嗯，加油！
