### ISSUE TITLE
类加载机制

### ISSUE THREAD

**Issue by ghost** [c-rainstorm/blog#4]
<JAVA_HOME>/jre/lib/rj.jar
是rt.jar吧

https://github.com/c-rainstorm/blog/blob/master/reading-notes/%E8%B0%88%E8%B0%88Java%E7%B1%BB%E5%8A%A0%E8%BD%BD%E6%9C%BA%E5%88%B6.md#overview

**Comment by c-rainstorm** [comment]
嗯，对的。是我笔误~
