### ISSUE TITLE
阿里面试成功了吗？

### ISSUE THREAD

**Issue by HeyHao** [c-rainstorm/blog#5]
看你只写到一面的面经，不知道二面怎么样了？
现在校招也开始了，应该进步很大，把握更大了吧

**Comment by c-rainstorm** [comment]
投实习二面一直没来，无奈~
有一定的进步，但是把握依旧没增大。所以阿里秋招想晚点投，但内推投太晚了好像，直接被回绝了，连面试机会都没有。听说阿里今年的名额特别少，内推都这样了，秋招网申基本也没太大希望了，只能加油投其他公司了。
你也加油，有心得可以一起交流啊~

**Comment by HeyHao** [comment]
现在主要是在牛客网上找一些内推

**Comment by c-rainstorm** [comment]
嗯嗯，加油!
