### ISSUE TITLE
interview  阿里面试  

### ISSUE THREAD

**Issue by QGB** [c-rainstorm/blog#6]
可不可以使用 epoll 主动发送请求

**Comment by QGB** [comment]
5.创建epoll，开启任务，发起请求等等，关注事件 
6.while大循环中使用epoll_wait返回活跃的事件，每个事件开启一个线程处理（线程中主要是解析页面，保存页面，url处理等），在线程结束的时候可能会开启新的任务。

**Comment by QGB** [comment]
epoll机制，是一种IO多路复用机制，可以同时监控多个描述符，当某个描述符就绪(读或写就绪)，则立刻通知相应程序进行读或写操作，本质同步I/O，即读写是阻塞的。

**Comment by c-rainstorm** [comment]
抱歉，之前对这块了解感觉太浅了，所以一直没有回复。

epoll监听的是文件上的事件，一般是读写事件。应用层想用这种模式的话，可以参考下 Reactor pattern

https://java-design-patterns.com/patterns/reactor/
http://www.dre.vanderbilt.edu/~schmidt/PDF/reactor-siemens.pdf
https://projectreactor.io/
