### ISSUE TITLE
拓展子目录数量的问题

### ISSUE THREAD

**Issue by LampScript** [c-rainstorm/blog#8]
Ext4 支持 64000 个子目录

我查了下应该是支持无限个的，因为目录下文件数量多到一定程度时会转成hash目录结构。
参考博客：https://bean-li.github.io/EXT4_DIR_INDEX/

**Comment by c-rainstorm** [comment]
嗯嗯，当时只是单纯的翻译。给你点个赞 ，👍

https://ext4.wiki.kernel.org/index.php/Ext4_Howto#Sub_directory_scalability

![image](https://user-images.githubusercontent.com/22186269/66019891-b7131380-e517-11e9-9b99-bf5146deb9a3.png)
https://en.wikipedia.org/wiki/Ext4#Features
